// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBXMk8L0t4s1oLbluN0Ljz7oPu85D2e0',
    appId: '1:764433102952:web:af12e6d95ef4b348ace3dd',
    messagingSenderId: '764433102952',
    projectId: 'group-talk-f508c',
    authDomain: 'group-talk-f508c.firebaseapp.com',
    storageBucket: 'group-talk-f508c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhH2V_EtkEJ-5PbHeIPCoUBnSI4dGv9eI',
    appId: '1:764433102952:android:cce5d67492044059ace3dd',
    messagingSenderId: '764433102952',
    projectId: 'group-talk-f508c',
    storageBucket: 'group-talk-f508c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-QhPHCTzMyLuYFmm4eHGwtMMJKZ8f6M',
    appId: '1:764433102952:ios:44bf6817432af954ace3dd',
    messagingSenderId: '764433102952',
    projectId: 'group-talk-f508c',
    storageBucket: 'group-talk-f508c.firebasestorage.app',
    iosBundleId: 'com.example.grouptalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL-QhPHCTzMyLuYFmm4eHGwtMMJKZ8f6M',
    appId: '1:764433102952:ios:44bf6817432af954ace3dd',
    messagingSenderId: '764433102952',
    projectId: 'group-talk-f508c',
    storageBucket: 'group-talk-f508c.firebasestorage.app',
    iosBundleId: 'com.example.grouptalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEBXMk8L0t4s1oLbluN0Ljz7oPu85D2e0',
    appId: '1:764433102952:web:17207a23e5dee1cface3dd',
    messagingSenderId: '764433102952',
    projectId: 'group-talk-f508c',
    authDomain: 'group-talk-f508c.firebaseapp.com',
    storageBucket: 'group-talk-f508c.firebasestorage.app',
  );
}
